### ISSUE TITLE
Website front page broken

### ISSUE THREAD

**Issue by szepeviktor** [cachewerk/relay-docs#2]
🚨 @tillkruss https://relay.so/

- includes https://ten-legendary.relay.so/script.js which is a HTTP/403
- inline scripts are CSP forbidden
- slider broken

![kép](https://user-images.githubusercontent.com/952007/211126477-0a9f51b6-9331-4ce2-a42a-c67d726c3707.png)

**Comment by szepeviktor** [comment]
The HTTP response `content-security-policy` header I've received.

```
default-src 'self' 'nonce-e9e7fa14196ba47d565b2263c24225a3' *.relay.so assets.relay.so; 
img-src 'self' data: *.relay.so assets.relay.so; 
connect-src 'self' *.relay.so *.algolia.net *.algolianet.com; 
report-uri https://o482380.ingest.sentry.io/api/5532530/security/?sentry_key=4001bfc17aa44d0b836d93b8b7003cf2&sentry_environment=production&sentry_release=04a1c4b
```

Try this tool: https://csp-evaluator.withgoogle.com/

**Comment by tillkruss** [comment]
I can't replicate any of this.

What browser are you using where the slider is broken?

**Comment by szepeviktor** [comment]
Firefox configured very-very strictly.
Is https://ten-legendary.relay.so/script.js a 403 for you too?

**Comment by szepeviktor** [comment]
@tillkruss You must know me that current reality does really touches my heart. I focus on long-term stable operations.
btw. Google Chrome is known to be "so user friendly" that is ignores standards.

**Comment by szepeviktor** [comment]
> current reality does really touches my heart

Please tell me if you wouldn't invest in the future!

**Comment by tillkruss** [comment]
> Firefox configured very-very strictly.

Right, the slider is broken in FF 👍

> Is https://ten-legendary.relay.so/script.js a 403 for you too?

200 for me when embedded.

**Comment by tillkruss** [comment]
> > current reality does really touches my heart
> 
> Please tell me if you wouldn't invest in the future!

I don't understand.

**Comment by szepeviktor** [comment]
I'd would add `script-src 'nonce-dda7308cda9f3196689dbb3db05fc6fa';` to our CSP.

**Comment by szepeviktor** [comment]
> I don't understand.

I care about every byte without looking at the browser window. I take my time and solve non-apparent problems too. #prevention

**Comment by szepeviktor** [comment]
Something fishy is going on!
`default-src 'nonce-e9e7fa14196ba47d565b2263c24225a3';` should be enough.
I have to dig deeper.

**Comment by szepeviktor** [comment]
@tillkruss I should cry! 😭 
https://bugzilla.mozilla.org/show_bug.cgi?id=1313937
Firefox does not handle the nonce in `default-src`.

Could you move the nonce to `script-src`? https://github.com/cachewerk/relay-docs/issues/2#issuecomment-1376028687
This is the short-term solution.

---

May I rethink the CSP of your website?

**Comment by tillkruss** [comment]
Yep, found the same issue. already in git 👍

**Comment by szepeviktor** [comment]
> May I rethink the CSP of your website?

The current CSP is permissive and implicit.
It would be nice to have a *perfect* one :) What do you think?

**Comment by tillkruss** [comment]
You mean make it stricter?
