### ISSUE TITLE
(public) release checklist

### ISSUE THREAD

**Issue by szepeviktor** [cachewerk/relay-docs#4]
Could we have a checklist that is updated and being used at each release?

tag, build, deploy, announce (blog, email, Wiki) etc.

For example WP-CLI guys are witty https://make.wordpress.org/cli/handbook/contributions/release-checklist/
They use a GitHub issue template.

**Comment by tillkruss** [comment]
We do have the release documented internally in a Wiki, could probably be improved tho.

**Comment by szepeviktor** [comment]
All right. The fun part is hidden from me!
