### ISSUE TITLE
Get included in PHPStorm stubs library

### ISSUE THREAD

**Issue by szepeviktor** [cachewerk/relay-docs#5]
It would be nice to appear here https://github.com/jetbrains/phpstorm-stubs

#release-checklist

**Comment by tillkruss** [comment]
Do you want to submit this?

https://builds.r2.relay.so/dev/relay.stub.php

**Comment by szepeviktor** [comment]
I think they support many PHP versions.
https://github.com/JetBrains/phpstorm-stubs/branches/active

Would you send them stubs only for PHP 8.2?

**Comment by tillkruss** [comment]
I see, let's submit 8.2 first, and later we can add 7.4, 8.0 and 8.1?

**Comment by tillkruss** [comment]
Merged.
